# test CI
# test code change: addition of env var
name: deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:  
  deploy:
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: "stable"
    
        - name: Checkout ci branch
          uses: actions/checkout@v4
          with:
            ref: ci

        - name: Build Web Application
          run: flutter build web -t lib/main_production.dart --dart-define TEST=https://tjvdjh92ap.us-east-1.awsapprunner.com

        - name: Copy Build Artifact
          run: |
            [[ -d artifact ]] && rm -r artifact
            mkdir artifact
            cp -R build/web artifact

        - name: Commit the Artifact
          uses: stefanzweifel/git-auto-commit-action@v5
          with:
            branch: ci
            commit_message: 'ci: automated commit at ${{ github.sha }}'