name: deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:  
  deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            persist-credentials: false

        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: "stable"

        - name: Get packages
          run: flutter pub get
    
        - name: Build Web Application
          run: flutter build web

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region:  ${{ secrets.AWS_REGION }}
        
        - name: Sync to S3
          run: aws s3 sync build/web s3://web-deploy-poc